name: Deploy PRODUCTION
on:
  push:
    branches:
      - main
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: NPM install
        run: npm install
      - name: NPM build
        run: npm run build
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_DEPLOYER_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_DEPLOYER_KEY_SECRET }}
          aws-region: eu-west-3
      - name: Copy files to s3 bucket
        run: |
          aws s3 sync build/ s3://cesc-cool-production/public/
          aws s3 cp build/index.html s3://cesc-cool-production/
      - name: Invalidate cache so CF stops serving old non existent versions
        # I thought it was something I miss configured, but it doesn't seem that easy...
        # more info https://aws.amazon.com/premiumsupport/knowledge-center/cloudfront-serving-outdated-content-s3/
        # tGoogling around seems that invalidation is the way to go
        run: |
          aws cloudfront create-invalidation --distribution-id EF4W7J97URLAN --paths '/index.html'
